server:
  port: 8081
  servlet:
    context-path: /nhom19

spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=webquanao;encrypt=false;trustServerCertificate=true
    username: sa
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        # ép dùng StandardImpl (không chuyển camel -> snake)
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        # thêm các key này để chắc chắn bị ghi đè
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.boot.model.naming: DEBUG
    org.hibernate.engine.jdbc.env.internal: DEBUG
    org.springframework.orm.jpa: DEBUG

jwt:
  signerKey: "g/Y81rnu6xcnhyvHBgPjWuqmR0H@oVbHqyp/Pc23s4gtJgu$2jK7FBsW+T#P/Y0Z6XYvbGLY0S3jD5s8Znmsdg=="
